version: '3'

services:
  app:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - postgres
      networks:
      - default

  postgres:
    image: postgres:latest
    environment:
      POSTGRES_PORT: 5432
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    networks:
      - default

  pgadmin:
    image: dpage/pgadmin4:8.6
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
      PGADMIN_LISTEN_PORT: 5050
    ports:
      - "5050:5050"
    depends_on:
      - postgres
    networks:
      - default

volumes:
  db_data:
    driver: ./data

networks:
  default:
    driver: bridge