version: '2.1'

services:
  postgres:
    image: postgres
    environment:
      POSTGRES_DB: mydb
      POSTGRES_USER: nz
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"

  node:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - postgres
    env_file:
      - .env

  pgadmin:
    image: dpage/pgadmin4:8.6
    ports:
      - "8080:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: enzo@enzo.com
      PGADMIN_DEFAULT_PASSWORD: admin
    depends_on:
      - postgres