version: '3'

services:
  app:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - db

  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: cesi_db
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
    ports:
      - "5432:5432"

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: postgresql
      POSTGRES_DB: cesi_db
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
    ports:
      - "8080:80"
    depends_on:
      - db